package pojos;
// Generated Dec 7, 2018 9:02:52 AM by Hibernate Tools 4.3.1



/**
 * Birthyear generated by hbm2java
 */
public class Birthyear  implements java.io.Serializable {


     private Integer artistId;
     private String firstName;
     private String lastName;
     private int yoB;

    public Birthyear() {
    }

    public Birthyear(String firstName, String lastName, int yoB) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.yoB = yoB;
    }
   
    public Integer getArtistId() {
        return this.artistId;
    }
    
    public void setArtistId(Integer artistId) {
        this.artistId = artistId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public int getYoB() {
        return this.yoB;
    }
    
    public void setYoB(int yoB) {
        this.yoB = yoB;
    }




}


